### PR TITLE
Dynamic *job-id* accessible by workers

### PR DESCRIPTION
**Pull request by jimbru**
Useful for logging and debugging. See commit log for more.

### CODE REVIEW

**Comment by ctdean** [comment]
So `id` comes from the PG column ?

**Comment by ctdean** [comment]
I think that we should move `*job-id*` to core.clj so that the user only has to import one namespace.

**Comment by ctdean** [comment]
+1

**Comment by jimbru** [comment]
Ditto on wanting `*job-id*` in core. The idea of a user having to import `engine` (which I consider to be opaque implementation) really bothers me. But I couldn't figure out a way to put `*job-id*` in `core` without either triggering a circular import error or a major refactor. Either Clojure is a bitch, or I'm dense, or both; but if you can figure out a good way to do it, then please enlighten me!

**Pull request merged**
